# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI
env:
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  JWT_TIMEOUT_DURATION: ${{ secrets.JWT_TIMEOUT_DURATION }}
  JWT_TOKEN_TEST: ${{ secrets.JWT_TOKEN_TEST }}
  MONGODB_URL: ${{ secrets.MONGODB_URL }}
  NEO4J_PW: ${{ secrets.NEO4J_PW }}
  NEO4J_URL: ${{ secrets.NEO4J_URL }}
  NEO4J_USR: ${{ secrets.NEO4J_USR }}

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run test
    
    - name: Render Deployment
      if: ${{ success() }}
      # You may pin to the exact commit or the version.
      # uses: sws2apps/render-deployment@cb4cce83b99653bee952b81acbba65ddfc9226d8
      uses: sws2apps/render-deployment@v1.1.0
      with:
        # The Service ID of your Render service
        serviceId: ${{ secrets.RENDER_SERVICE_ID }}
        # Your personal API key to interact with Render
        apiKey: ${{ secrets.RENDER_API_KEY }}
